import type { ExperienceScene } from './types';

export const happinessScenes: readonly ExperienceScene[] = [
  {
    id: 'partner-cooked-without-expensive-gift',
    title: '伴侣没送贵重礼物，却做了饭',
    domain: '情感',
    observableFact: '纪念日这天，对方没有准备贵重礼物，但提前买菜做了一顿你爱吃的饭。',
    primaryKey: { id: 1, title: '幸福是一种情绪' },
    firstThoughts: [
      {
        id: 'not-valued',
        label: '他根本不重视我，连礼物都舍不得',
        likelyDirection: '把爱的价值直接等同于礼物价格，容易让一顿真实的用心变成新的争吵。',
      },
      {
        id: 'compare',
        label: '别人都有惊喜，我怎么这么委屈',
        likelyDirection: '用别人的表达方式衡量自己的关系，委屈会压过眼前已经发生的照顾。',
      },
      {
        id: 'settle',
        label: '我是不是只能接受这种低配的爱',
        likelyDirection: '把一次表达方式推成整段关系的结论，会让需求表达变成防御和冷战。',
      },
    ],
    acknowledgement: '纪念日想被认真对待，这是很自然的期待；失落感可以被看见。',
    strengthView: '他没有用贵重礼物表达，也许用的是更朴素的照顾：记得你的口味，愿意花时间做一顿饭。',
    evidencePrompt: '这顿饭里有没有一个细节，能说明对方知道你喜欢什么、忌口什么，或提前准备过？',
    boundary: '看见做饭的心意，不等于取消你对仪式感、惊喜和被珍惜的合理表达。',
    newThought: '礼物可以很闪，饭菜也可以很真；幸福不只挂在价格牌上，也藏在有人愿意为你忙一阵的烟火里。',
    newExpression: '今天我有一点想要礼物的失落，但我也看见你认真做了这顿饭，谢谢你记得我爱吃这个。',
    commentExpression: '你今天为我做饭这个小动作，很踏实，也很有生活里的担当感。',
    microAction: '先夸一句饭里的具体细节，再约一个轻松时间聊你想要的仪式感。',
    nextSceneCue: '下一次伴侣用朴素方式表达关心时。',
    passCriteria: [
      '先说出饭菜里一个具体被照顾到的细节。',
      '表达需求时不使用“你从来不重视我”。',
      '约定下次纪念日一个可执行的小仪式。',
    ],
  },
  {
    id: 'friend-promotion-house-post',
    title: '朋友升职买房发朋友圈',
    domain: '社交',
    observableFact: '朋友在朋友圈发了升职和买房的消息，配文感谢家人和一路努力。',
    primaryKey: { id: 2, title: '幸福是正确的对比' },
    firstThoughts: [
      {
        id: 'behind',
        label: '别人都起来了，只有我还在原地',
        likelyDirection: '把朋友的高光拿来对照自己的低谷，容易让祝福变成自我否定。',
      },
      {
        id: 'unfair',
        label: '他也没比我强多少，凭什么这么顺',
        likelyDirection: '把差距解释成不公平，会让你错过对方身上可学习的稳定行动。',
      },
      {
        id: 'show-off',
        label: '发出来不就是炫耀吗',
        likelyDirection: '先把分享解读成炫耀，关系会变薄，自己的心也会越看越苦。',
      },
    ],
    acknowledgement: '看到朋友的好消息时心里一紧，不代表你小气，可能是你也很想过得更好。',
    strengthView: '这条朋友圈也许不只是炫耀，可能是一个人把多年努力终于落地的开心拿出来分享。',
    evidencePrompt: '他的文字里有没有感谢、复盘、长期努力，还是只有单纯比较和压人一头？',
    boundary: '正确对比不是让你假装不羡慕，也不是忽视自己的现实压力，而是换一个能帮助行动的参照物。',
    newThought: '朋友的高光不是我的判决书，它更像一盏路灯：提醒我也可以找一个更清楚的下一步。',
    newExpression: '看见你这一步真的不容易，尤其还能记得感谢家人。替你高兴，也向你的坚持学习。',
    commentExpression: '你这次分享里最打动我的，是成功之后还记得感谢身边人，这份清醒很难得。',
    microAction: '给朋友留一句真诚祝福，再写下自己本周能推进的一件小事。',
    nextSceneCue: '下一次刷到别人生活高光时。',
    passCriteria: [
      '先写下一句不带讽刺的祝福。',
      '说出对方一个可学习的具体行为。',
      '把比较改成自己本周一个可执行动作。',
    ],
  },
  {
    id: 'partner-two-hours-no-reply',
    title: '伴侣两个小时没有回复消息',
    domain: '情感',
    observableFact: '你发出消息后，对方两个小时没有回复；之前对方说今天工作安排比较满。',
    primaryKey: { id: 3, title: '幸福是心态平衡' },
    firstThoughts: [
      {
        id: 'ignored',
        label: '他就是故意不理我',
        likelyDirection: '把未回复直接解释成故意冷落，会让你带着怒气追问，对方更容易防御。',
      },
      {
        id: 'not-love',
        label: '真在乎我的人不可能这么久不回',
        likelyDirection: '把回复速度当作爱的唯一证明，期待越紧，关系里的压力越大。',
      },
      {
        id: 'revenge',
        label: '那我也不回他，看谁更冷',
        likelyDirection: '用冷处理回应不安，短期像赢了，长期会让沟通变成拉扯。',
      },
    ],
    acknowledgement: '等消息时不安和失落很真实，尤其当你很需要回应的时候。',
    strengthView: '对方没有立刻回复，可能和工作节奏、注意力被占用有关；你愿意等待，也说明你在乎这段连接。',
    evidencePrompt: '过去他忙完后是否会补充说明？今天有没有会议、路上、照顾家人等具体安排？',
    boundary: '理解忙碌不等于接受长期失联；重要事情仍然需要共同约定回复规则。',
    newThought: '两个小时没有回复，说明此刻没有回复，不必立刻判成没有爱；我可以先稳住自己，再把需求说清。',
    newExpression: '我刚才等得有点着急。你忙完回我一下就好，我们也可以约个重要消息的回复方式。',
    commentExpression: '你今天能提前说工作满，说明你不是完全不交代，这个意识我看见了。',
    microAction: '先放下手机十分钟，做一件手边事；十分钟后只发一句不攻击的提醒。',
    nextSceneCue: '下一次对方没有在你期待时间内回复时。',
    passCriteria: [
      '没有连续发送三条以上质问消息。',
      '用“我有点着急”表达感受，而不是“你故意”。',
      '提出一个具体回复约定供双方讨论。',
    ],
  },
  {
    id: 'family-work-no-thanks',
    title: '我为家里做了很多，却没人感谢',
    domain: '家庭',
    observableFact: '你做饭、收拾、安排家务，家人吃完后各自去忙，没有主动说谢谢。',
    primaryKey: { id: 4, title: '幸福是一种相互给予' },
    firstThoughts: [
      {
        id: 'unseen',
        label: '他们都把我的付出当成应该的',
        likelyDirection: '长期看不见感谢，会让付出从爱变成账本，话一出口就容易带刺。',
      },
      {
        id: 'quit',
        label: '以后我什么都不做了',
        likelyDirection: '用停止付出表达委屈，短期能出气，长期会让家庭协作更僵。',
      },
      {
        id: 'poor-me',
        label: '这个家只有我一个人在撑',
        likelyDirection: '把所有责任都压在自己身上，既累坏自己，也堵住了家人参与的机会。',
      },
    ],
    acknowledgement: '做了很多却没人回应，委屈不是矫情；人都需要被看见。',
    strengthView: '你愿意照顾家里，也许说明你有责任心和经营家庭的能力；家人没说谢谢，也可能只是习惯了安稳。',
    evidencePrompt: '有没有某个家人实际享受了你的安排，或用别的方式回应过，只是没有说出口？',
    boundary: '给予不等于无限承担；家务分工、休息权和被感谢的需要，都可以清楚提出来。',
    newThought: '我的付出有价值，不必靠抱怨证明；我可以把“没人懂我”换成“我来教大家看见和分担”。',
    newExpression: '今天这顿饭我花了不少心思。你们吃得开心我也开心，不过我也想听到一句谢谢，明天我们一起分担一点。',
    commentExpression: '你们能安心吃饭、各自去忙，背后也说明这个家被照顾得很稳，这份稳定我今天也看见了。',
    microAction: '今晚只提出一个具体分担请求，比如饭后谁收碗，不翻旧账。',
    nextSceneCue: '下一次自己默默做完一件家务时。',
    passCriteria: [
      '先说清自己做了哪一件具体事。',
      '只提出一个可分担的小动作。',
      '不使用“这个家只有我一个人”做总结。',
    ],
  },
  {
    id: 'career-repeated-setbacks',
    title: '求职或创业连续碰壁',
    domain: '事业',
    observableFact: '你连续投递、面试或推进项目，但最近几次都没有得到理想结果。',
    primaryKey: { id: 5, title: '幸福是生命的动力' },
    firstThoughts: [
      {
        id: 'useless',
        label: '我是不是根本不行',
        likelyDirection: '把连续碰壁解释成自我无能，会让行动力快速掉下去。',
      },
      {
        id: 'late',
        label: '现在才开始已经太晚了',
        likelyDirection: '把阶段困难看成终局，会让你提前退出本来还可调整的路。',
      },
      {
        id: 'pointless',
        label: '努力也没用，不如算了',
        likelyDirection: '把短期无结果推成努力无意义，会切断复盘和改策略的可能。',
      },
    ],
    acknowledgement: '连续受挫会消耗人，这种疲惫需要被认真对待。',
    strengthView: '你还在投递、面试或推进，也许说明生命动力没有消失，只是需要一个更小的火种重新点起来。',
    evidencePrompt: '最近哪一次反馈里出现了可改的线索，比如简历、话术、客户画像或产品定位？',
    boundary: '转念不替代现实策略；必要时要调整方向、寻求专业建议，或给自己安排休息。',
    newThought: '碰壁不是给我判死刑，它是在告诉我：这条路的某个环节需要换打法，而我还没真正出局。',
    newExpression: '这几次没成挺打击我，但我至少看见自己还在往前试。下一步我先改一个环节。',
    commentExpression: '你连续碰壁还愿意复盘，这不是失败者的样子，这是一个人还没放弃自己的证据。',
    microAction: '十分钟内只改简历、话术或方案里的一个最明显问题。',
    nextSceneCue: '下一次收到拒绝、冷回复或项目卡住时。',
    passCriteria: [
      '说出一个可修改的具体环节。',
      '当天完成一个十分钟以内的小调整。',
      '没有用“我根本不行”给自己定性。',
    ],
  },
  {
    id: 'parents-repeat-reminders',
    title: '父母反复叮嘱让我心烦',
    domain: '家庭',
    observableFact: '父母反复提醒你吃饭、穿衣、工作、婚恋或安全，语气有时显得啰嗦。',
    primaryKey: { id: 6, title: '幸福是生活的颜色' },
    firstThoughts: [
      {
        id: 'control',
        label: '他们就是想控制我',
        likelyDirection: '把所有叮嘱都听成控制，会让关心也变成刺耳的噪音。',
      },
      {
        id: 'annoying',
        label: '太烦了，每次都这些话',
        likelyDirection: '只看见重复和唠叨，容易错过话背后的牵挂和不放心。',
      },
      {
        id: 'not-grown',
        label: '他们根本不把我当成年人',
        likelyDirection: '把提醒解读成否定成熟，会让你用顶撞证明独立。',
      },
    ],
    acknowledgement: '成年人被反复提醒，确实会烦，也会想要空间和尊重。',
    strengthView: '父母的表达可能笨拙，但反复叮嘱里也许藏着牵挂、责任感和害怕你受苦的心。',
    evidencePrompt: '他们提醒的内容，是否多和健康、安全、生活稳定有关，而不只是评价你这个人？',
    boundary: '看见牵挂不等于接受越界干涉；隐私、选择和边界仍然要温和但清楚。',
    newThought: '同一句叮嘱听成控制，心里全是烦；听见牵挂，生活的颜色就多了一层温度。',
    newExpression: '我知道你们是担心我。这个提醒我收到了，但这个决定我想自己来安排。',
    commentExpression: '你们反复提醒这件小事，背后其实是很深的牵挂和责任感，我听见了。',
    microAction: '先回应一句“我知道你担心”，再说一个具体边界。',
    nextSceneCue: '下一次父母重复提醒同一件事时。',
    passCriteria: [
      '先复述父母担心的具体内容。',
      '不用“你们烦死了”作为第一句回应。',
      '说出一个清楚可执行的边界。',
    ],
  },
  {
    id: 'wait-success-for-happiness',
    title: '总想等成功以后再幸福',
    domain: '个人成长',
    observableFact: '你常把放松、庆祝、陪伴家人和照顾自己放到“等成功以后”。',
    primaryKey: { id: 7, title: '幸福在每一天、不在某一天' },
    firstThoughts: [
      {
        id: 'not-qualified',
        label: '我现在还不配享受',
        likelyDirection: '把幸福设成奖品，会让每一天都像在还债，越努力越干。',
      },
      {
        id: 'later',
        label: '等我真的成功了再说',
        likelyDirection: '把幸福推到某一天，今天的连接、健康和小成就都会被长期搁置。',
      },
      {
        id: 'guilt',
        label: '休息一下我就有罪恶感',
        likelyDirection: '把休息看成偷懒，生命动力会被持续透支。',
      },
    ],
    acknowledgement: '想把事情做好、想赢一次，这份上进心很真实，也很辛苦。',
    strengthView: '你对成功有追求，也许说明你有责任感和目标感；现在要练的是让幸福成为燃料，而不是终点奖杯。',
    evidencePrompt: '今天有没有一件小事，哪怕只有五分钟，能让你恢复一点能量或连接？',
    boundary: '当下幸福不是放弃目标，也不是逃避责任；它是给长期行动补上能量。',
    newThought: '幸福不必等人生通关才发放；今天存进幸福银行的一点光，会变成明天继续走的力气。',
    newExpression: '我今天不等成功以后再开心了，先把这一个小完成记录下来，也谢谢自己没停下。',
    commentExpression: '你还在为目标坚持，这份认真值得被看见；也请把照顾自己当成能力的一部分。',
    microAction: '十分钟内记录今天一个具体完成，或给重要的人发一句感谢。',
    nextSceneCue: '下一次你想把休息和开心推到成功以后时。',
    passCriteria: [
      '当天记录一件已经完成的小事。',
      '安排一个十分钟以内的恢复动作。',
      '没有用“我不配”否定自己的基本需要。',
    ],
  },
  {
    id: 'cold-attitude-at-work',
    title: '同事或伴侣对我态度冷淡',
    domain: '工作',
    observableFact: '你打招呼或沟通事情时，对方回应很短，表情冷淡，没有继续展开。',
    primaryKey: { id: 8, title: '幸福是一种吸引力' },
    firstThoughts: [
      {
        id: 'targeted',
        label: '他一定是对我有意见',
        likelyDirection: '把冷淡直接解释成针对，自己会先紧绷，互动也更容易变硬。',
      },
      {
        id: 'worthless',
        label: '是不是我哪里不招人喜欢',
        likelyDirection: '把对方状态变成自我价值判断，会让你过度讨好或退缩。',
      },
      {
        id: 'payback',
        label: '他冷我也冷，没必要热脸贴冷屁股',
        likelyDirection: '用冷回应冷，表面保护自己，实际会让关系温度继续下降。',
      },
    ],
    acknowledgement: '被冷淡对待会不舒服，人都希望自己的善意有回应。',
    strengthView: '对方冷淡可能和压力、疲惫或正在处理别的事有关；你能觉察气氛，说明你很在意关系质量。',
    evidencePrompt: '对方只是这一次回应短，还是长期稳定地回避你？有没有工作压力或时间紧的线索？',
    boundary: '保持温度不等于讨好；如果对方持续不尊重或影响协作，需要事实化沟通。',
    newThought: '别人的冷淡不一定是我的失败；我可以先带着稳定和善意出现，让关系有一个重新升温的入口。',
    newExpression: '你现在可能有点忙，我先把重点说清楚。需要我配合的地方你直接告诉我。',
    commentExpression: '你虽然话不多，但能把事情回应到点上，这种简洁在忙的时候也挺有效率。',
    microAction: '下一句只讲事实和请求，不追问对方情绪。',
    nextSceneCue: '下一次对方回应短、表情冷时。',
    passCriteria: [
      '先确认一个可观察事实，而不是猜测对方讨厌你。',
      '用简短请求推进事情。',
      '没有用冷战回应对方的短回应。',
    ],
  },
  {
    id: 'same-conflict-repeats',
    title: '同类冲突反复发生',
    domain: '个人成长',
    observableFact: '你发现自己在亲密关系、家庭或工作里，反复因为相似的话题爆发争吵。',
    primaryKey: { id: 9, title: '幸福是人生的第一堂必修课' },
    firstThoughts: [
      {
        id: 'bad-luck',
        label: '为什么我总遇到这样的人',
        likelyDirection: '把重复冲突全归因于别人，会让自己错过改变入口。',
      },
      {
        id: 'no-change',
        label: '反正说了也没用，谁都不会变',
        likelyDirection: '把过去的失败当成未来定律，会让你继续用老方式得到老结果。',
      },
      {
        id: 'explode',
        label: '我忍太久了，这次必须说狠一点',
        likelyDirection: '用更重的话突破僵局，常常只会让对方记住伤害，忘掉问题本身。',
      },
    ],
    acknowledgement: '同样的矛盾一再出现，真的会让人无力，也会怀疑关系还有没有希望。',
    strengthView: '你已经能发现“反复发生”，也许说明你开始看见模式了；看见模式，就是智慧开门前的一下敲门。',
    evidencePrompt: '这类冲突爆发前，你通常说的第一句话、做的第一个动作是什么？结果是否总差不多？',
    boundary: '学习转念不等于把责任全揽到自己身上；涉及伤害、操控或持续失衡时，需要支持和边界。',
    newThought: '老问题反复出现，不只是命不好，也可能是在提醒我：换一句开场白，人生就可能换一条路。',
    newExpression: '我发现我们又卡在同一个点上了。这次我想先停一下，只说事实和需要，不互相定罪。',
    commentExpression: '你愿意回到这个问题上，其实说明你还在乎结果，也还有把关系修好的责任心。',
    microAction: '暂停十秒，只说“这次我先不翻旧账，我想说眼前这件事”。',
    nextSceneCue: '下一次你发现同类争吵又要开始时。',
    passCriteria: [
      '指出这次冲突的一个重复模式。',
      '换掉过去最容易引爆的第一句话。',
      '至少停十秒再继续表达需求。',
    ],
  },
  {
    id: 'child-exam-setback',
    title: '孩子考试没有考好',
    domain: '亲子',
    observableFact: '这次分数不理想；孩子拿到试卷后，主动标记并订正了错题。',
    primaryKey: { id: 10, title: '幸福是打开智慧之门的钥匙' },
    firstThoughts: [
      {
        id: 'lazy',
        label: '他就是不努力，说多少遍都没用',
        likelyDirection: '把一次成绩直接解释为不努力，着急很容易变成指责，孩子会更想躲开问题。',
      },
      {
        id: 'future',
        label: '这次都考不好，以后怎么办',
        likelyDirection: '把一次失利推演成整个未来，焦虑会压过眼前真正可以补上的知识点。',
      },
      {
        id: 'shame',
        label: '别人家的孩子都比他省心',
        likelyDirection: '用别人家的孩子作参照，容易让比较代替沟通，也削弱孩子继续尝试的勇气。',
      },
    ],
    acknowledgement: '看到分数不理想，你着急，是因为你在乎孩子的未来。',
    strengthView: '主动标记并订正错题，也许说明他没有躲开问题，愿意重新弄懂。',
    evidencePrompt: '他是否真的完成了订正，并能说出至少一道错题卡在哪里？',
    boundary: '看见订正的力量，不等于忽略学习习惯和仍需解决的知识漏洞。',
    newThought: '一次分数只能暴露这次学习中的问题，不能替孩子的一生下结论；这张卷子没替他说好话，但他没有躲开它。',
    newExpression: '这次分数不理想，但我看见你在主动订正。我们先把最容易补上的那一题弄懂。',
    commentExpression: '你拿到试卷后愿意标错题、改错题，这说明你有面对问题的勇气和补上的心。',
    microAction: '先只问一道题：“你最想先弄懂哪一道？”然后听完再给建议。',
    nextSceneCue: '下一次孩子带回一张分数不理想的试卷时。',
    passCriteria: [
      '先说出一个试卷上真实可见的成长动作。',
      '只问一道孩子愿意先处理的错题。',
      '听完回答前，不比较、不追加第二个要求。',
    ],
  },
  {
    id: 'stranger-small-help',
    title: '陌生人提供微小帮助',
    domain: '社交',
    observableFact: '陌生人帮你扶了一下门、提醒你东西掉了，或在排队时让你先处理急事。',
    primaryKey: { id: 11, title: '传播幸福的能力' },
    firstThoughts: [
      {
        id: 'nothing',
        label: '这点小事没什么，不用当回事',
        likelyDirection: '把善意看得太小，容易错过生活里可以被放大的温暖。',
      },
      {
        id: 'suspicious',
        label: '他是不是有什么目的',
        likelyDirection: '过度防备会保护你，也可能让普通善意被自动拦在门外。',
      },
      {
        id: 'awkward',
        label: '我不知道怎么回应，算了',
        likelyDirection: '把感谢吞回去，会让善意停在自己这里，没有继续流动。',
      },
    ],
    acknowledgement: '对陌生人的帮助保持一点谨慎很正常，尤其在不熟悉的环境里。',
    strengthView: '这个小动作可能说明对方有观察力和公共善意；你愿意回应，也可以把幸福传出去一点。',
    evidencePrompt: '这个帮助是否具体、短暂、没有越界要求，也没有索取隐私或利益？',
    boundary: '感谢善意不等于放下安全判断；涉及金钱、隐私、跟随或身体接触时要保持边界。',
    newThought: '幸福有时不是大礼物，而是一秒钟的善意；我接住它，再轻轻传出去，世界就亮一点。',
    newExpression: '谢谢你刚才提醒我，这个小动作很及时，也很暖。',
    commentExpression: '你刚才愿意停一下提醒别人，这份细心和公共善意很难得。',
    microAction: '当场说一句具体谢谢，并在今天主动做一个不越界的小帮助。',
    nextSceneCue: '下一次收到陌生人的小提醒或小帮助时。',
    passCriteria: [
      '感谢时说出对方做的具体小行为。',
      '不泄露隐私、不接受越界要求。',
      '当天主动完成一个安全的小善意。',
    ],
  },
  {
    id: 'promotion-not-recognized',
    title: '没升职、没被认可',
    domain: '事业',
    observableFact: '这次升职或表彰名单里没有你，但你近期完成了一个稳定交付的项目。',
    primaryKey: { id: 12, title: '幸福不要外求、交换、条件和只要结果' },
    firstThoughts: [
      {
        id: 'invisible',
        label: '我做再多也没人看见',
        likelyDirection: '把一次没有被认可解释成永远没价值，会让你带着怨气工作。',
      },
      {
        id: 'politics',
        label: '全靠关系，努力没意义',
        likelyDirection: '把结果完全归因于关系，会让你失去复盘影响力和表达价值的机会。',
      },
      {
        id: 'quit-care',
        label: '那我以后就随便做做',
        likelyDirection: '用降低质量保护自尊，可能让真实能力也被一起埋掉。',
      },
    ],
    acknowledgement: '努力没有得到对应认可，会失落、愤怒，也会怀疑值不值得继续。',
    strengthView: '稳定交付本身可能说明你有可靠性、责任感和解决问题的能力；这些价值不该只由一次名单决定。',
    evidencePrompt: '这个项目里有没有可量化的结果、被他人使用的成果，或客户同事的具体反馈？',
    boundary: '不把幸福绑死在结果上，不等于不争取机会；晋升规则、反馈和资源仍然可以主动沟通。',
    newThought: '外部认可很重要，但它不是我价值的唯一开关；我可以先把成果说清，再去争取该争取的。',
    newExpression: '这次没进入名单我有失落。也想和你复盘一下，我这个项目的价值和下一次晋升需要补齐的标准。',
    commentExpression: '你能把项目稳定交付下来，这份可靠不是热闹的光，但它是团队真正能踩得住的地。',
    microAction: '列出项目三个事实成果，预约一次不抱怨的反馈沟通。',
    nextSceneCue: '下一次努力没有马上得到认可时。',
    passCriteria: [
      '先列出三个项目事实成果。',
      '提出一次具体反馈沟通请求。',
      '没有用“努力没意义”否定全部行动。',
    ],
  },
];
